# THIS IS THE BYTECODE RUNNER. IT RUNS THE BYTECODE GENERATED BY THE COMPILER.
# SLOWER THAN THE INTERPRETER, BUT IT IS A STEP TOWARDS A JIT COMPILER.
# THE BYTECODE COMPILER IS NOT OPTIMIZED, AND IT IS PROBABLY SLOWER THAN THE INTERPRETER BECAUSE OF THIS.
from lexer import lex
from parser import Parser
from bComp import VM, Compiler
import os
import time

# os.system('cls')
# times = []
# for i in range(10):
code_lines = []


code_name = "code.or"


# Get the path to the TESTS(Or) directory relative to this script
base_dir = os.path.dirname(os.path.abspath(__file__))
tests_dir = os.path.join(base_dir, "..", "TESTS(Or)")

with open(os.path.join(tests_dir, code_name), 'r') as file:
        for line in file:
            code_lines.append(line.strip())

# 1. Tokenize the code
start_time = time.perf_counter()
tokens = lex(code_lines)
end_time = time.perf_counter()
# for i in tokens:
#     print(i)
# 2. Parse tokens into an AST
start_time1 = time.perf_counter()
parser = Parser(tokens)
ast = parser.program()
end_time1 = time.perf_counter()
# print(ast)
start_time2 = time.perf_counter()
# 3. Compile AST to bytecode

compiler = Compiler()  
compiler.compile(ast)
end_time2 = time.perf_counter()
# compiler.print()
# 4. Run bytecode on VM
start_time3 = time.perf_counter()
vm = VM(compiler.bytecode, compiler.constants)
# print(compiler.bytecode)
vm.run()

end_time3 = time.perf_counter()

# Calculate the elapsed time


elapsed_time = end_time - start_time
print(f"Lexing completed in {elapsed_time:.4f} seconds.")

elapsed_time1 = end_time1 - start_time1
print(f"Parsing completed in {elapsed_time1:.4f} seconds.")

elapsed_time2 = end_time2 - start_time2
print(f"Compilation completed in {elapsed_time2:.4f} seconds.")

elapsed_time3 = end_time3 - start_time3
print(f"Execution completed in {elapsed_time3:.4f} seconds.")   

print(f"Total time is {elapsed_time+elapsed_time1+elapsed_time2+elapsed_time3:.4f} seconds")