# THIS IS THE BYTECODE RUNNER. IT RUNS THE BYTECODE GENERATED BY THE COMPILER.
# SLOWER THAN THE INTERPRETER, BUT IT IS A STEP TOWARDS A JIT COMPILER.
# THE BYTECODE COMPILER IS NOT OPTIMIZED, AND IT IS PROBABLY SLOWER THAN THE INTERPRETER BECAUSE OF THIS.
import sys
from pathlib import Path
if __name__ == '__main__' and __package__ is None:
    sys.path.append(str(Path(__file__).resolve().parent.parent))

from origin.lexer import lex
from origin.parser import Parser
from origin.ir_gen import ir_gen
import os
import time

# os.system('cls')
# times = []
# for i in range(10):
code_lines = []


code_name = "code.or"


# Get the path to the TESTS(Or) directory relative to this script
base_dir = os.path.dirname(os.path.abspath(__file__))
tests_dir = os.path.join(base_dir, "..", "TESTS(Or)")

with open(os.path.join(tests_dir, code_name), 'r') as file:
        for line in file:
            code_lines.append(line.strip())

# 1. Tokenize the code
start_time = time.perf_counter()
tokens = lex(code_lines)
# for i in tokens:
#     print(i)
# 2. Parse tokens into an AST
parser = Parser(tokens)
ast = parser.program()
print(ast)

irGen = ir_gen()
irGen.generate(ast)
print(irGen.code)
end_time = time.perf_counter()
# Calculate the elapsed time
elapsed_time = end_time - start_time

print(f"seconds elapsed: {elapsed_time}s")
# times.append(elapsed_time) 
# for i in range(len(times)):
#     print(f"Run {i+1}: {times[i]:.4f} seconds") 

